version: "3.9"
services:

  app:
<<<<<<< HEAD
    build: app/
=======
    build: WebService/
>>>>>>> main
    volumes:
      - type:   volume
        source: trusted-orchestrator-volume
        target: /tmp
    ports:
      - 80:80
    depends_on:
      vault-server:
        condition: service_healthy
      trusted-orchestrator:
        condition: service_healthy
      database:
        condition: service_healthy
      secure-service:
        condition: service_healthy

  vault-server:
    build: ./setup/vault-server/
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      APPROLE_ROLE_ID:         demo-web-app
      ORCHESTRATOR_TOKEN:      insecure_token
      DATABASE_HOSTNAME:       database
      DATABASE_PORT:           1433
    ports:
      - 8200:8200
    depends_on:
      database:
        condition: service_healthy

  trusted-orchestrator:
    build: ./setup/trusted-orchestrator
    environment:
      VAULT_ADDRESS:      http://vault-server:8200
      ORCHESTRATOR_TOKEN: insecure_token
    volumes:
      - type:   volume
        source: trusted-orchestrator-volume
        target: /tmp
    depends_on:
      vault-server:
        condition: service_healthy

  database:
    image: mcr.microsoft.com/mssql/server:latest
    init: true
    environment:
      ACCEPT_EULA:        y
      DATABASE_HOSTNAME:  localhost
      DATABASE_PORT:      1433
      SA_PASSWORD:        DatabaseAdminPassword1
    volumes:
      - type:    bind
        source:  setup/database
        target:  /home/database/.
    command: [
      "bash",
      "-c",
      "( /home/database/populate.sh && touch /tmp/healthy ) & /opt/mssql/bin/sqlservr"
    ]
    ports:
      - 1433:1433
    healthcheck:
      test:         bash -c "[ -f /tmp/healthy ]"
      start_period: 1s
      interval:     1s
      timeout:      1s
      retries:      30

  # secure-service is a simulated 3rd party service that requires a specific header to get a 200 response
  secure-service:
    image: nginx:latest
    environment:
      EXPECTED_API_KEY: my-secret-key # sets the expected value for incoming requests' header X-API-KEY
    volumes:
      - type:   bind
        source: ./setup/secure-service/default.conf.template
        target: /etc/nginx/templates/default.conf.template
    ports:
      - 8080:80
    healthcheck:
      test:         curl --fail -s http://localhost/healthcheck || exit 1
      start_period: 1s
      interval:     1s
      timeout:      1s
      retries:      30

volumes:
  trusted-orchestrator-volume:
