version: "3.9"
services:
  api-service:
    build: ApiProject/
    depends_on:
      - vault
      - db
    ports:
      - 8080:8080
    volumes:
      - type: volume
        source: trusted-orchestrator-volume
        target: /tmp
    entrypoint: ./wait-for-vault.sh
  # secure-service is a simulated 3rd party service that requires a specific header to get a 200 response
  secure-service:
    image: nginx:latest
    volumes:
      - type:      bind
        source:    ./setup/nginx/default.conf.template
        target:    /etc/nginx/templates/default.conf.template
    ports:
      - "1717:80"
    environment:
      # EXPECTED_API_KEY sets the expected value for incoming requests' header X-API-KEY
      EXPECTED_API_KEY: my-secret-key
  db:
    image: mcr.microsoft.com/mssql/server:latest
    init: true
    environment:
      ACCEPT_EULA:  y
      SA_PASSWORD:  DatabaseAdminPassword1
    volumes:
      - type:    bind
        source:  ./setup/db-data
        target:  /home/db-data/.
    command: [ "bash", "-c", "( /home/db-data/populate.sh && touch /tmp/healthy ) & /opt/mssql/bin/sqlservr"  ]
    ports:
      - 1433:1433
    healthcheck:
      test: [ "CMD", "bash", "-c", "[ -f /tmp/healthy ]" ]

  vault:
    build: ./setup/vault-server/
    volumes:
      - type:   volume
        source: trusted-orchestrator-volume
        target: /tmp
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      ORCHESTRATOR_TOKEN:      insecure_token
      APPROLE_ROLE_ID:         demo-web-app
      DB_HOST: "db"
  trusted-orchestrator:
    build: ./setup/trusted-orchestrator
    depends_on:
      - vault
    environment:
      ORCHESTRATOR_TOKEN: insecure_token
    volumes:
      - type: volume
        source: trusted-orchestrator-volume
        target: /tmp

volumes:
  dbdata:
  trusted-orchestrator-volume: