version: "3.9"
services:
  app:
    build: ApiProject/.
    environment:
      MY_ADDRESS:                   :8080
      VAULT_ADDRESS:                http://vault:8200
    ports:
      - "8080:8080"
    depends_on:
      - db
      - vault
      - secure-service
  db: 
    image: mcr.microsoft.com/mssql/server:2017-latest
    restart: always
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - 1433:1433
  vault:
    image: vault:latest
    restart: always
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=root
    ports:
      - 8200:8200 
  # secure-service is a simulated 3rd party service that requires a specific header to get a 200 response
  secure-service:
    image: nginx:latest
    volumes:
      - type:      bind
        source:    ./setup/nginx/default.conf.template
        target:    /etc/nginx/templates/default.conf.template
    ports:
      - "1717:80"
    environment:
      # EXPECTED_API_KEY sets the expected value for incoming requests' header X-API-KEY
      EXPECTED_API_KEY: my-secret-key
volumes:
  dbdata:
  vaultdata: 