version: "3.9"
services:
  api:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db
      - vault
  db: 
    image: mcr.microsoft.com/mssql/server:2017-latest
    restart: always
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - 1433:1433
  vault:
    image: vault:latest
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=root
    ports:
      - 8200:8200