version: "3.9"
services:

  api-service:
    build: ApiProject/
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8080:8080

  db:
    image: mcr.microsoft.com/mssql/server:latest
    init: true
    environment:
      ACCEPT_EULA:  y
      SA_PASSWORD:  DatabaseAdminPassword1
    volumes:
      - type:    bind
        source:  setup/db-data
        target:  /home/db-data/.
    command: [ "bash", "-c", "( /home/db-data/populate.sh && touch /tmp/healthy ) & /opt/mssql/bin/sqlservr"  ]
    ports:
      - 1433:1433
    healthcheck:
      test: [ "bash", "-c", "[ -f /tmp/healthy ]" ]

  vault:
    image: vault:latest
    restart: always
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
    cap_add:
      - IPC_LOCK
    ports:
      - 8200:8200
